name: Deploy Applications

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Initial Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

  verify-vue:
    name: Test Vue App
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies for Vue
        run: |
          cd vue
          npm install

      - name: Run Vue Tests
        run: |
          cd vue
          npm run test

  verify-svelte:
    name: Test Svelte App
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies for Svelte
        run: |
          cd svelte
          npm install

      - name: Run Svelte Tests
        run: |
          cd svelte
          npm run test

  deploy-vue:
    name: Deploy Vue App
    runs-on: ubuntu-latest
    needs: verify-vue # Only runs if Vue passes tests

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies for Vue
        run: |
          cd vue
          npm install

      - name: Build Vue Project
        run: |
          cd vue
          npm run build

      - name: Deploy Vue to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_VUE }}
          working-directory: vue

  deploy-svelte:
    name: Deploy Svelte App
    runs-on: ubuntu-latest
    needs: verify-svelte 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies for Svelte
        run: |
          cd svelte
          npm install

      - name: Build Svelte Project
        run: |
          cd svelte
          npm run build

      - name: Deploy Svelte to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_SVELTE }}
          working-directory: svelte
