name: Deploy Applications

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: Initial Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

  verify-vue:
    name: Test Vue App
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies for Vue
        run: |
          cd vue
          npm install

      - name: Run Vue Tests
        run: |
          cd vue
          npm run test
          
  verify-svelte:
    name: Test Svelte App
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies for Svelte
        run: |
          cd svelte
          npm install

      - name: Run Svelte Tests
        run: |
          cd svelte
          npm run test

  e2e-vue:
    name: E2E Tests – Vue App
    runs-on: ubuntu-latest
    needs: verify-vue

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          cd e2e/vue_tests
          npm install

      - name: Install Playwright Browsers
        run: |
          cd e2e/vue_tests
          npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          cd e2e/vue_tests
          npx playwright test

  e2e-svelte:
    name: E2E Tests – Svelte App
    runs-on: ubuntu-latest
    needs: verify-svelte

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: |
          cd e2e/svelte_tests
          npm install

      - name: Install Playwright Browsers
        run: |
          cd e2e/svelte_tests
          npx playwright install --with-deps

      - name: Run Playwright Tests
        run: |
          cd e2e/svelte_tests
          npx playwright test                

  deploy-vue:
    name: Deploy Vue App
    runs-on: ubuntu-latest
    needs: [verify-vue, e2e-vue]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies for Vue
        run: |
          cd vue
          npm install

      - name: Build Vue Project
        run: |
          cd vue
          npm run build

      - name: Deploy Vue to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_VUE }}

  deploy-svelte:
    name: Deploy Svelte App
    runs-on: ubuntu-latest
    needs: [verify-svelte, e2e-svelte] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies for Svelte
        run: |
          cd svelte
          npm install

      - name: Build Svelte Project
        run: |
          cd svelte
          npm run build

      - name: Deploy Svelte to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_SVELTE }}